apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
  - name: foobar-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      echo "Starting log simulation";
      for i in 1 2 3 4 5 6 7 8 9 10; do
        if [ $i -eq 5 ]; then
          echo "Error: unable-to-access-website";
        else
          echo "Info: Operation $i completed successfully";
        fi;
        sleep 1;
      done;
      echo "Log simulation finished";
      tail -f /dev/null; # 这行代码是被添加的，用于保持容器运行
    imagePullPolicy: IfNotPresent
