apiVersion: v1
kind: Pod
metadata:
  name: 11-factor-app
spec:
  containers:
    - name: logger
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do
            echo "$(date) - This is a sample log message" >> /var/log/11-factor-app.log;
            sleep 5;
          done