apiVersion: v1
kind: Pod
metadata:
  name: cpu-utilization-1rug
  labels: 
    name: cpu-loader
spec:
  containers:
  - name: cpu-utilization-container
    image: busybox
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    command: ["/bin/sh"]
    args: ["-c", "while true; do :; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-utilization-gu8c
  labels: 
    name: cpu-loader
spec:
  containers:
  - name: cpu-utilization-container
    image: busybox
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "500m"
    command: ["/bin/sh"]
    args: ["-c", "while true; do :; done"]
