apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location /hello {
          return 200 'hello';
      }

      location / {
          return 404;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config-volume
        configMap:
          name: hello-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
  - port: 5678
    targetPort: 80
  selector:
    app: hello
